### ISSUE TITLE
incremental strategy

### ISSUE THREAD

**Issue by briceburg** [ncw/rclone#18]
Hi Nick,

I'm currently using s3ql to mount remote S3/GCS data as a local filesystem (through fuse), and then use a [shell script](https://github.com/iceburg-net/ansible-pcd/blob/master/roles/pcd-apps/backup/templates/backup_sites.sh.j2) to implement rsync based backups to this filesystem.

I'd like to make use of rclone based backups in ansible-pcd -- for its simplicity and for user friendliness (e.g. browsing on the remote end will display the backed up files themselves -- versus s3ql which displays indecipherable filesystem metadata).

For the majority of "backups", it's important to have incremental functionality that allows you to a restore a file from "yesterday" w/o having "todays" changes override and make that impossible. E.g. snapshots/rotations/&c. 

Most incremental strategies  also make subsequent backups efficient by limiting what gets backed up to changed components only; speeding up runtime and transfer time, and saving space @ the backup destination.

Protecting against file corruption making its way into downstream [snapshots/rotations/&c] is also a plus.

I think rclone handles the syncing component well -- although don't see anything apparent re: incremental snapshotting.  Do you plan to implement or could you share your thoughts on this feature? 

Thanks!

**Comment by briceburg** [comment]
My initial thought is to use remote-to-remote for this, e.g.

First Backup ("base")
```
rclone copy /path/to/backup remote:/backups/base
```

Subsequent  Backups
```
date=`date "+%Y%m%d_%H:%M:%S"`
rclone sync remote:/backups/base remote:/backups/$date
rclone sync /path/to/backup remote:/backups/$date
```

Not sure about the efficiency of the remote-to-remote. Bad idea?

Also,  the README indicates:
```
Deletes any files that exist in source that don't exist in destination.
```

I'm used to behavior that deletes files that exist in the target destination that do not exist in the source destination. Worried that the rclone behavior would remove [new] files from /path/to/backup ...

Thanks!

**Comment by ncw** [comment]
Your idea for the remote to remote copy is how I would approach it.

This has one disdvantage with rclone as it stands today in that it will effectively download the data and re-upload it.  However I have been thinking about an allowing bucket to bucket copies which would be exactly what you want.  S3, Swift and GCS all allow this.  Here is the docs for GCS

**Comment by briceburg** [comment]
Nick,

Great! This is pretty exciting. Bucket-to-bucket copying sounds promising. What about this approach as well;

`rclone sync /path/to/backup remote:/backups/base remote:/backups/changes.2015-01-19`

Where rclone would compare /path/to/backup against remote:/backups/base  , and copy changes to remote:/backups/changes-2015-01-19

Obviously this would mess with the deletes behavior, which could be dealt with by adding a flag that would remove deleted files from remote:/backups/base, and optionally preserving them elsewhere (e.g. copying them to remote:/backups/deleted-files ). We could then run a janitorial command that removes files older than X days from remote:/backups/deleted-files ) ... **and also take advantage of bucket-to-bucket copying  without incurring the cost of doubling storage space with each snapshot  **

**Comment by ncw** [comment]
Interesting idea!

I think I'd simplify the logic slightly and make it a new rclone command

    rclone sync3 /path/to/backup remote:/backups/base remote:/backups/changes.2015-01-19

  * for every file in/path/to/backup
    * if it is in base unchanged - skip
    * if it is modified in base
      * copy the file from base to changes if it exists in base
      * upload the file to base
  * for every file in base but not in backup
    * move it from base to changes

This would mean that base would end up with a proper sync of backup, but changes would have any old files which changed or were deleted.  It would then effectively be a delta, and you would have all the files at both points in time.

You could re-create the old filesystem easily, except for if you uploaded new files into base - there would be no way of telling just by looking at base and changes that those new files where new or just unchanged old files.  This may or may not be a problem!

**Comment by briceburg** [comment]
Nick,

Right -- totally agree re: new rclone command for this. The precursor is getting bucket-to-bucket functionality.

Just FYI, I'm super excited about rclone && am loving your work. For now, I'm going to go with an incredibly simple approach to backups with rclone.

basically I'll have two targets, one that is synced weekly, and one that is synced daily. E.g. my cron will look like;

```
10     2     *     *     *  rclone sync ~/VAULT google:vault/nesta/daily
10     4     *     *     0  rclone sync ~/VAULT google:vault/nesta/weekly
```

This will [hopefully] preserve deleted files in the weekly snapshot. Could also add a monthly &c.

I think this will work for now, but certainly interested in helping with bucket-to-bucket and incremental strategies. If I can help, please let me know. May need to learn Go :)

**Comment by briceburg** [comment]
I've added ansible scripts to 1) install rclone  and 2) implement the above backup strategy on a crontab based system (still need to make a systemd timer compatible version for archlinux &c). Sharing for fun.

Install rclone:
```
---

- name: install rclone 
  hosts: all
  sudo: true
  sudo_user: root
 
  vars:
    # check http://rclone.org/downloads/ for latest...
    rclone_version: 1.07
    rclone_vstr: rclone-v{{ rclone_version }}-linux-amd64
    rclone_target: /opt/rclone/{{ rclone_vstr }}
 
  pre_tasks:
    - stat: path={{ rclone_target }}
      register: stat_rclone 

  tasks:
    - name: download rclone
      uri:
        dest=/tmp/
        follow_redirects=all
        url=http://downloads.rclone.org/{{ rclone_vstr }}.zip
      when: not stat_rclone.stat.exists
   
    - name: unpack rclone
      command: unzip /tmp/{{ rclone_vstr }}.zip -d /opt/rclone
        creates={{ rclone_target }}

    - name: add rclone to path
      file:
        state=link
        dest=/usr/local/bin/rclone
        src={{ rclone_target }}/rclone
```

Backup Stategy
```
---
- name: vault backup 
  hosts: all

  vars:
    vault_base: "google:iceburg-vault/{{ TARGET_USER }}"
    vault_daily: "{{ vault_base }}/daily" 
    vault_weekly: "{{ vault_base }}/weekly"

  tasks:
    - name: $HOME/.rclone.conf
      file:
        state=link
        dest={{ TARGET_USER_HOME }}/.rclone.conf
        src={{ DOTFILES_DIR }}/.rclone.conf
        force={{ FORCE_LINKS }}

    - name: fetch vault
      command: rclone copy {{ vault_daily }} ~/VAULT
        creates=~/VAULT

    - name: schedule daily vault backup
      cron:
        name="daily vault backup"
        minute=40
        hour=4
        job="rclone sync ~/VAULT {{ vault_daily }}"

    - name: schedule weekly vault backup
      cron:
        name="weekly vault backup"
        minute=40
        hour=5
        job="rclone sync ~/VAULT {{ vault_weekly }}"
```
