### ISSUE TITLE
mount and cmount tests not running on travis

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2100]
The mount and cmount tests aren't being run on travis.

The cmount test is running on appveyor.

The mount integration test is running on the integration test server - hopefully now it will run the cmount test too: https://github.com/rclone/integration-test/commit/e6b9a9056eb79ef99cb32095f96affcea03508f6

The problem is that FUSE does not work without `sudo: required`

**NB** if building with cmount then don't want to make the linux binaries dynamic - cross compile should take care of that - better check though!

[This config may work](https://github.com/travis-ci/travis-ci/issues/1100)

```yaml
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf`
```
