### ISSUE TITLE
Fix Debian packages: broken control fields

### ISSUE THREAD

**Issue by aptituz** [ncw/rclone#2172]
#### What is the problem you are having with rclone?

The Debian packages contains debian control information which has *syntax errors*.

In particular the debian/control of the package contains fields which have no values for basically all relationships:

``` 
dpkg-deb -I rclone-v1.40-linux-amd64.deb |grep -E 'Depends|Replaces|Recommends|Suggests|Conflicts'
 Replaces: 
 Depends: 
 Recommends: 
 Suggests: 
 Conflicts: 
```
Since that does not comply with the format specification (https://www.debian.org/doc/debian-policy/#document-ch-controlfields) it leads to problems once those packages are added to a custom repository. 

In that case the packages affect unrelated software since apt will no longer be able to install packages (at least from that repo).

#### What is your rclone version (eg output from `rclone -V`)

The package version is v1.40 for amd64.
